require_relative 'user'        #Model class
require_relative 'tweet'
require_relative 'retweet'
require_relative 'hashtag'
require_relative 'follow'
require_relative 'mention'
require_relative 'favourite'
require_relative 'conversation'
require_relative 'chat_group'
require_relative 'message'